CREATE SEQUENCE SEQ_BOARD_SN
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE TABLE TB_BOARD
(
  BOARD_SN     NUMBER,
  TITLE        VARCHAR2(200 BYTE),
  CONTENTS     VARCHAR2(4000 BYTE),
  CREATE_DATE  DATE,
  CREATE_USER  VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TB_BOARD_PK ON TB_BOARD
(BOARD_SN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TB_BOARD ADD (
  CONSTRAINT TB_BOARD_PK
  PRIMARY KEY
  (BOARD_SN)
  USING INDEX TB_BOARD_PK
  ENABLE VALIDATE);
